### ISSUE TITLE
SIGABRT in druntime-test-thread/tlsgc_sections on x86 musl

### ISSUE THREAD

**Issue by Cogitri** [ldc-developers/ldc#3404]
Test with LDC 1.20.1. Here's the backtrace:

```
#0  __cp_end () at src/thread/i386/syscall_cp.s:31
#1  0xf7fbc1e4 in __syscall_cp_c (nr=240, u=-136647880, v=128, w=2, x=0, y=0, z=0) at src/thread/pthread_cancel.c:33
#2  0xf7fbb547 in __futex4_cp (to=0x0, val=<optimized out>, op=<optimized out>, addr=<optimized out>)
    at src/thread/__timedwait.c:24
#3  __timedwait_cp (addr=0xf7daeb38, val=2, clk=1, at=0x0, priv=128) at src/thread/__timedwait.c:52
#4  0xf7fbc62d in __pthread_cond_timedwait (c=0xf7db100c, m=0xf7db000c, ts=0x0)
    at src/thread/pthread_cond_timedwait.c:100
#5  0xf7fbc925 in pthread_cond_wait (c=0xf7db100c, m=0xf7db000c) at src/thread/pthread_cond_wait.c:5
#6  0x5655c016 in core.sync.condition.Condition.wait() ()
#7  0x5655b90d in tlsgc_sections.test() ()
#8  0x5655cc52 in thread_entryPoint ()
#9  0xf7fbcd30 in start (p=0xf7daec64) at src/thread/pthread_create.c:192
#10 0xf7fbb7b8 in __clone () at src/thread/i386/clone.s:37
#11 0x00000000 in ?? ()
```

**Comment by Cogitri** [comment]
This happens on x86_64 too with 1.21.0

**Comment by tom-tan** [comment]
I confirmed this was fixed in ldc 1.39.0 on x86_64.
- https://gitlab.alpinelinux.org/tom-tan/aports/-/jobs/1446982#L4803

I am not sure it was fixed on x86.
